language: python
sudo: required
dist: xenial
python:
  - "3.7"
before_install:
  - "export DISPLAY=:99.0"
install:
  - pip install -r requirements.txt
  - pip install coverage codacy-coverage
script:
 - isort -c -rc
 - pycodestyle modules/ tests/ *.py*
 - xvfb-run nosetests --with-coverage --cover-erase --cover-package=modules --cover-html
after_success:
  - coverage report -m
  - coverage xml
  - export CODACY_PROJECT_TOKEN=28c624d32d36476ab7d0e9c831318127
  - python-codacy-coverage -r coverage.xml
