language: python
cache: pip
os: linux
dist: bionic
services:
  - xvfb
python:
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install coverage codacy-coverage
  - sudo apt-get install strace
script:
  - isort . --diff
  - pycodestyle modules/ tests/ *.py*
  - QT_QPA_PLATFORM=offscreen strace -f xvfb-run -a --server-args="-screen 0 1024x768x24" nosetests --with-coverage --cover-erase --cover-package=modules --cover-html
after_success:
  - coverage report -m
  - coverage xml
  - export CODACY_PROJECT_TOKEN=28c624d32d36476ab7d0e9c831318127
  - python-codacy-coverage -r coverage.xml
