language: python
sudo: required
dist: xenial
addons:
  apt:
    packages:
    - libxkbcommon-x11-0
python:
  - "3.8"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb herbstluftwm
install:
  - pip install -r requirements.txt
  - pip install coverage codacy-coverage
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
  - sleep 3
before_script:
  - "herbstluftwm &"
  - sleep 1
script:
 - isort . --diff
 - pycodestyle modules/ tests/ *.py*
 - nosetests --with-coverage --cover-erase --cover-package=modules --cover-html
after_success:
  - coverage report -m
  - coverage xml
  - export CODACY_PROJECT_TOKEN=28c624d32d36476ab7d0e9c831318127
  - python-codacy-coverage -r coverage.xml
