# -*- coding: utf-8 -*-

try:
    from PyQt6 import QtCore, QtWidgets
    from PyQt6.QtWidgets import QSizePolicy
    from PyQt6.QtGui import QAction
except ImportError as err:
    from PyQt5 import QtCore, QtWidgets
    from PyQt5.QtWidgets import QSizePolicy, QAction
    print(f"mainwindow.py: ImportError {err=}, {type(err)=}")
except Exception as err:
    print(f"mainwindow.py: Unexpected {err=}, {type(err)=}")
    raise


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setObjectName("MainWindow")
        self.resize(785, 769)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(507, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_user = QtWidgets.QLabel(self.centralwidget)
        self.label_user.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_user.setObjectName("label_user")
        self.verticalLayout.addWidget(self.label_user)
        self.tableView_user = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableView_user.sizePolicy().hasHeightForWidth())
        self.tableView_user.setSizePolicy(sizePolicy)
        self.tableView_user.setObjectName("tableView_user")
        self.verticalLayout.addWidget(self.tableView_user)
        self.pushButton_user = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_user.setObjectName("pushButton_user")
        self.verticalLayout.addWidget(self.pushButton_user)
        self.pushButton_edituser = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_edituser.setObjectName("pushButton_edituser")
        self.verticalLayout.addWidget(self.pushButton_edituser)
        self.pushButton_deleteuser = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deleteuser.setObjectName("pushButton_deleteuser")
        self.verticalLayout.addWidget(self.pushButton_deleteuser)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 5)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        self.menuEvaluation = QtWidgets.QMenu(self.menubar)
        self.menuEvaluation.setObjectName("menuEvaluation")
        self.setMenuBar(self.menubar)
        self.actionExit = QAction(self)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QAction(self)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QAction(self)
        self.actionSave.setObjectName("actionSave")
        self.actionNew = QAction(self)
        self.actionNew.setObjectName("actionNew")
        self.actionInfo = QAction(self)
        self.actionInfo.setObjectName("actionInfo")
        self.actionOverview = QAction(self)
        self.actionOverview.setObjectName("actionOverview")
        self.actionPrintPreview = QAction(self)
        self.actionPrintPreview.setObjectName("actionPrintPreview")
        self.actionLoad_file = QAction(self)
        self.actionLoad_file.setObjectName("actionLoad_file")
        self.actionSave_file_as = QAction(self)
        self.actionSave_file_as.setObjectName("actionSave_file_as")
        self.actionCreateCertificates = QAction(self)
        self.actionCreateCertificates.setObjectName("actionCreateCertificates")
        self.actionXLSX_Export = QAction(self)
        self.actionXLSX_Export.setObjectName("actionXLSX_Export")
        self.actionCreateAddress = QAction(self)
        self.actionCreateAddress.setObjectName("actionCreateAddress")
        self.menuFile.addAction(self.actionExit)
        self.menuInfo.addAction(self.actionInfo)
        self.menuEvaluation.addAction(self.actionOverview)
        self.menuEvaluation.addAction(self.actionPrintPreview)
        self.menuEvaluation.addAction(self.actionXLSX_Export)
        self.menuEvaluation.addSeparator()
        self.menuEvaluation.addAction(self.actionCreateAddress)
        self.menuEvaluation.addAction(self.actionCreateCertificates)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEvaluation.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Archerrank2"))
        self.label_user.setText(_translate("MainWindow", "participants"))
        self.pushButton_user.setText(_translate("MainWindow", "add new user"))
        self.pushButton_edituser.setText(_translate("MainWindow", "edit user"))
        self.pushButton_deleteuser.setText(_translate("MainWindow", "delete user"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuInfo.setTitle(_translate("MainWindow", "I&nfo"))
        self.menuEvaluation.setTitle(_translate("MainWindow", "E&valuation"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionNew.setText(_translate("MainWindow", "&New"))
        self.actionInfo.setText(_translate("MainWindow", "&Info"))
        self.actionOverview.setText(_translate("MainWindow", "&Overview"))
        self.actionPrintPreview.setText(_translate("MainWindow", "&Print Preview"))
        self.actionLoad_file.setText(_translate("MainWindow", "&Load file"))
        self.actionSave_file_as.setText(_translate("MainWindow", "&Save file as"))
        self.actionCreateCertificates.setText(_translate("MainWindow", "&Create certificates"))
        self.actionXLSX_Export.setText(_translate("MainWindow", "XLSX Export"))
        self.actionCreateAddress.setText(_translate("MainWindow", "Create Address"))
