# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 769)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(507, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_user = QtWidgets.QLabel(self.centralwidget)
        self.label_user.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user.setObjectName("label_user")
        self.verticalLayout.addWidget(self.label_user)
        self.tableView_user = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableView_user.sizePolicy().hasHeightForWidth())
        self.tableView_user.setSizePolicy(sizePolicy)
        self.tableView_user.setObjectName("tableView_user")
        self.verticalLayout.addWidget(self.tableView_user)
        self.pushButton_user = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_user.setObjectName("pushButton_user")
        self.verticalLayout.addWidget(self.pushButton_user)
        self.pushButton_edituser = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_edituser.setObjectName("pushButton_edituser")
        self.verticalLayout.addWidget(self.pushButton_edituser)
        self.pushButton_deleteuser = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deleteuser.setObjectName("pushButton_deleteuser")
        self.verticalLayout.addWidget(self.pushButton_deleteuser)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 5)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        self.menuEvaluation = QtWidgets.QMenu(self.menubar)
        self.menuEvaluation.setObjectName("menuEvaluation")
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.actionOverview = QtWidgets.QAction(MainWindow)
        self.actionOverview.setObjectName("actionOverview")
        self.actionPrintPreview = QtWidgets.QAction(MainWindow)
        self.actionPrintPreview.setObjectName("actionPrintPreview")
        self.actionLoad_file = QtWidgets.QAction(MainWindow)
        self.actionLoad_file.setObjectName("actionLoad_file")
        self.actionSave_file_as = QtWidgets.QAction(MainWindow)
        self.actionSave_file_as.setObjectName("actionSave_file_as")
        self.actionCreateCertificates = QtWidgets.QAction(MainWindow)
        self.actionCreateCertificates.setObjectName("actionCreateCertificates")
        self.actionXLSX_Export = QtWidgets.QAction(MainWindow)
        self.actionXLSX_Export.setObjectName("actionXLSX_Export")
        self.actionCreateAddress = QtWidgets.QAction(MainWindow)
        self.actionCreateAddress.setObjectName("actionCreateAddress")
        self.menuFile.addAction(self.actionExit)
        self.menuInfo.addAction(self.actionInfo)
        self.menuEvaluation.addAction(self.actionOverview)
        self.menuEvaluation.addAction(self.actionPrintPreview)
        self.menuEvaluation.addAction(self.actionXLSX_Export)
        self.menuEvaluation.addSeparator()
        self.menuEvaluation.addAction(self.actionCreateAddress)
        self.menuEvaluation.addAction(self.actionCreateCertificates)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEvaluation.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Archerrank2"))
        self.label_user.setText(_translate("MainWindow", "participants"))
        self.pushButton_user.setText(_translate("MainWindow", "add new user"))
        self.pushButton_edituser.setText(_translate("MainWindow", "edit user"))
        self.pushButton_deleteuser.setText(_translate("MainWindow", "delete user"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuInfo.setTitle(_translate("MainWindow", "I&nfo"))
        self.menuEvaluation.setTitle(_translate("MainWindow", "E&valuation"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionNew.setText(_translate("MainWindow", "&New"))
        self.actionInfo.setText(_translate("MainWindow", "&Info"))
        self.actionOverview.setText(_translate("MainWindow", "&Overview"))
        self.actionPrintPreview.setText(_translate("MainWindow", "&Print Preview"))
        self.actionLoad_file.setText(_translate("MainWindow", "&Load file"))
        self.actionSave_file_as.setText(_translate("MainWindow", "&Save file as"))
        self.actionCreateCertificates.setText(_translate("MainWindow", "&Create certificates"))
        self.actionXLSX_Export.setText(_translate("MainWindow", "XLSX Export"))
        self.actionCreateAddress.setText(_translate("MainWindow", "Create Address"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
